spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
moviefun:
  datasources:
    movies:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: root
      password:
    albums:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: root
      password: